# inputs
sourceCode: JS Source Code
queries: Queries

Static Analysis Engine: {
  cpg: Graph Construction
  queryExec: Query Execution Engine

  cpg -> queryExec
}

sourceCode -> Static Analysis Engine.cpg
queries -> Static Analysis Engine.queryExec

Symbolic Execution Engine: {
  cpg: Graph Construction
  queryExec: Query Execution Engine

  cpg -> queryExec
}
